export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SAVE = 'ORDER_CREATE_SAVE'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SAVE = 'ORDER_DETAILS_SAVE'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'