export const PRODUCT_SEED_LIST_REQUEST = 'PRODUCT_SEED_LIST_REQUEST'
export const PRODUCT_SEED_LIST_SUCCESS = 'PRODUCT_SEED_LIST_SUCCESS'
export const PRODUCT_SEED_LIST_FAIL = 'PRODUCT_SEED_LIST_FAIL'

export const PRODUCT_SEED_DETAILS_REQUEST = 'PRODUCT_SEED_DETAILS_REQUEST'
export const PRODUCT_SEED_DETAILS_SUCCESS = 'PRODUCT_SEED_DETAILS_SUCCESS'
export const PRODUCT_SEED_DETAILS_FAIL = 'PRODUCT_SEED_DETAILS_FAIL'

export const PRODUCT_MACHINE_LIST_REQUEST = 'PRODUCT_MACHINE_LIST_REQUEST'
export const PRODUCT_MACHINE_LIST_SUCCESS = 'PRODUCT_MACHINE_LIST_SUCCESS'
export const PRODUCT_MACHINE_LIST_FAIL = 'PRODUCT_MACHINE_LIST_FAIL'

export const PRODUCT_MACHINE_DETAILS_REQUEST = 'PRODUCT_MACHINE_DETAILS_REQUEST'
export const PRODUCT_MACHINE_DETAILS_SUCCESS = 'PRODUCT_MACHINE_DETAILS_SUCCESS'
export const PRODUCT_MACHINE_DETAILS_FAIL = 'PRODUCT_MACHINE_DETAILS_FAIL'