// SEEDS
export const PRODUCT_SEED_LIST_REQUEST = 'PRODUCT_SEED_LIST_REQUEST'
export const PRODUCT_SEED_LIST_SUCCESS = 'PRODUCT_SEED_LIST_SUCCESS'
export const PRODUCT_SEED_LIST_FAIL = 'PRODUCT_SEED_LIST_FAIL'

export const PRODUCT_SEED_DETAILS_REQUEST = 'PRODUCT_SEED_DETAILS_REQUEST'
export const PRODUCT_SEED_DETAILS_SUCCESS = 'PRODUCT_SEED_DETAILS_SUCCESS'
export const PRODUCT_SEED_DETAILS_FAIL = 'PRODUCT_SEED_DETAILS_FAIL'

export const SEED_DELETE_REQUEST = 'SEED_DELETE_REQUEST'
export const SEED_DELETE_SUCCESS = 'SEED_DELETE_SUCCESS'
export const SEED_DELETE_FAIL = 'SEED_DELETE_FAIL'


// LEND MACHINES
export const PRODUCT_MACHINE_LIST_REQUEST = 'PRODUCT_MACHINE_LIST_REQUEST'
export const PRODUCT_MACHINE_LIST_SUCCESS = 'PRODUCT_MACHINE_LIST_SUCCESS'
export const PRODUCT_MACHINE_LIST_FAIL = 'PRODUCT_MACHINE_LIST_FAIL'

export const PRODUCT_MACHINE_DETAILS_REQUEST = 'PRODUCT_MACHINE_DETAILS_REQUEST'
export const PRODUCT_MACHINE_DETAILS_SUCCESS = 'PRODUCT_MACHINE_DETAILS_SUCCESS'
export const PRODUCT_MACHINE_DETAILS_FAIL = 'PRODUCT_MACHINE_DETAILS_FAIL'

export const MACHINE_DELETE_REQUEST = 'MACHINE_DELETE_REQUEST'
export const MACHINE_DELETE_SUCCESS = 'MACHINE_DELETE_SUCCESS'
export const MACHINE_DELETE_FAIL = 'MACHINE_DELETE_FAIL'

// CONSUMER
export const CONSUMER_PRODUCT_LIST_REQUEST = 'CONSUMER_PRODUCT_LIST_REQUEST'
export const CONSUMER_PRODUCT_LIST_SUCCESS = 'CONSUMER_PRODUCT_LIST_SUCCESS'
export const CONSUMER_PRODUCT_LIST_FAIL = 'CONSUMER_PRODUCT_LIST_FAIL'

export const CONSUMER_PRODUCT_DETAILS_REQUEST = 'CONSUMER_PRODUCT_DETAILS_REQUEST'
export const CONSUMER_PRODUCT_DETAILS_SUCCESS = 'CONSUMER_PRODUCT_DETAILS_SUCCESS'
export const CONSUMER_PRODUCT_DETAILS_FAIL = 'CONSUMER_PRODUCT_DETAILS_FAIL'

export const CONSUMER_DELETE_REQUEST = 'CONSUMER_DELETE_REQUEST'
export const CONSUMER_DELETE_SUCCESS = 'CONSUMER_DELETE_SUCCESS'
export const CONSUMER_DELETE_FAIL = 'CONSUMER_DELETE_FAIL'