export const SUPPLIER_PRODUCT_CREATE_REQUEST = 'SUPPLIER_PRODUCT_CREATE_REQUEST'
export const SUPPLIER_PRODUCT_CREATE_SUCCESS = 'SUPPLIER_PRODUCT_CREATE_SUCCESS'
export const SUPPLIER_PRODUCT_CREATE_FAIL = 'SUPPLIER_PRODUCT_CREATE_FAIL'

export const SUPPLIER_PRODUCT_LIST_REQUEST = 'SUPPLIER_PRODUCT_LIST_REQUEST'
export const SUPPLIER_PRODUCT_LIST_SUCCESS = 'SUPPLIER_PRODUCT_LIST_SUCCESS'
export const SUPPLIER_PRODUCT_LIST_FAIL = 'SUPPLIER_PRODUCT_LIST_FAIL'

export const SUPPLIER_PRODUCT_LIST_MY_REQUEST = 'SUPPLIER_PRODUCT_LIST_MY_REQUEST'
export const SUPPLIER_PRODUCT_LIST_MY_SUCCESS = 'SUPPLIER_PRODUCT_LIST_MY_SUCCESS'
export const SUPPLIER_PRODUCT_LIST_MY_FAIL = 'SUPPLIER_PRODUCT_LIST_MY_FAIL'